root: 
  - financial_institution:
    name: 'Simplii'
    url: 'https://www.simplii.com/en/rates.html'
    div: 'div'
    id:  'accounts'
    table: 'table'
    accounts:
      - account:
        account_name: 'No Fee Chequing Account'
        xpath: 'none'
      - account:
        account_name: 'Overdraft'
        xpath: 'none'
      - account:
        account_name: 'High Interest Savings Account'
        xpath: '//*[@id="accounts"]/div[68]/div/div'
      - account:
        account_name: 'Simplii Financial Savings Account'
        xpath: 'none'


  - financial_institution:
    name: 'CIBC'
    url: 'https://www.cibc.com/en/interest-rates/personal-bank-account-rates.html'
    id: 'none'
    table: "table"
    accounts:
      - account:
        account_name: 'eAdvantage_Savings'
        xpath: '//*[@id="blq-content"]/div[5]'
      - account: 
        account_name: 'Bonus_Savings'
        xpath: '//*[@id="blq-content"]/div[6]'
      - account:
        account_name: 'Premium_Growth'
        xpath: '//*[@id="blq-content"]/div[7]'
      - account:
        account_name: 'US_Personal'
        xpath: '//*[@id="blq-content"]/div[10]'

  - financial_institution:
    name: 'RBC'
    url: 'http://www.rbcroyalbank.com/rates/persacct.html'
    accounts:
      - account:
        account_name: 'High_Interest_eSavings'
        xpath: '/html/body/table[1]/tbody/tr/td[2]/table/tbody/tr[2]/td/table/tbody/tr[4]/td[2]/table[1]'
      - account: 
        account_name: 'Enhanced_Savings'
        xpath: '/html/body/table[1]/tbody/tr/td[2]/table/tbody/tr[2]/td/table/tbody/tr[4]/td[2]/table[2]'
      - account:
        account_name: 'Day_To_Day_Savings'
        xpath: '/html/body/table[1]/tbody/tr/td[2]/table/tbody/tr[2]/td/table/tbody/tr[4]/td[2]/table[3]'
      - account:
        account_name: 'US_Personal'
        xpath: '/html/body/table[1]/tbody/tr/td[2]/table/tbody/tr[2]/td/table/tbody/tr[4]/td[2]/table[12]'
      - account:
        account_name: 'US_High_Interest_eSavings'
        xpath: '/html/body/table[1]/tbody/tr/td[2]/table/tbody/tr[2]/td/table/tbody/tr[4]/td[2]/table[13]'
   
   - financial_instituion:
     name: 'TDCT'
     url: 'https://www.tdcanadatrust.com/products-services/banking/accounts/account-rates.jsp'
     accounts:
      - account:
        account_name: 'Everyday Savings Account'
        xpath: 
      - account: 
        account_name: 'High Interest Savings Account'
        xpath:
      - account:
        account_name: 'ePremium Savings Account'
        xpath:
        
   -  financial_institution:
      name: 'BMO'
      url: 'https://www.bmo.com/main/personal/bank-accounts/savings/interest-rates/'
      - account:
        account_name: 'Savings Builder Account'
        xpath:
      - account:
        account_name: 'Smart Saver Account'
        xpath:
      - account:
        account_name: 'Premium Rate Savings Account'
        xpath: 
      
   -  financial_institution:
      name: 'BNS'
      url: 'https://www.scotiabank.com/ca/en/personal/rates-prices/savings-account-rates.html'
      - account:
      account_name: 'Scotiabank MomentumPLUS Savings Account'
      xpath: 
      - account:
      account_name: 'Money Master Savings Account'
      xpath: 
      - account:
      account_name: 'Scotiabank Savings Accelerator Account'
      xpath: 
      
   -  financial_institution:
      name: 'Tangerine'
      url: 'https://www.tangerine.ca/en/rates/'
      - account:
      account_name: 'Tangerine Savings Account'
      xpath: 

   -  financial_institution:
      name: 'ICICI'
      url: 'https://www.icicibank.ca/personalbanking/popup_sav.page'
      - account:
      account_name: 'ICICI HiSave Savings Account'
      xpath: 
      - account:
      account_name: 'ICICI Premium Savings Account'
      xpath: 
      - account:
      account_name: 'ICICI Young Stars Savings Account'
      xpath: 
      
   -  financial_institution:
      name: 'National Bank'
      url: 'https://www.nbc.ca/en/rates-and-analysis/interest-rates-and-returns/bank-accounts.html'
      - account:
      account_name: 'High-Interest Savings Account'
      xpath: 
      
   -  financial_institution:
      name: 'Manulife'
      url: 'https://www.manulifebank.ca/current-rates.html'
      - account:
      account_name: 'Advantage Account' 
      xpath:       
      
   -  financial_institution:
      name: 'HSBC'
      url: 'https://www.hsbc.ca/savings-accounts/rates/'
      - account:
      account_name: 'High Rate Savings'
      xpath:       
      
   -  financial_institution:
      name: 'CDN TIRE'
      url: 'https://www.myctfs.com/Rates/'
      - account:
      account_name: 'High Interest Savings Account'
      xpath: 

