root: 
  - financial_institution:
    name: 'Simplii'
    url: 'https://www.simplii.com/en/rates.html'
    div: 'div'
    id:  'accounts'
    table: 'table'
    accounts:
      - account:
        account_name: 'No Fee Chequing Account'
        xpath: 'none'
      - account:
        account_name: 'Overdraft'
        xpath: 'none'
      - account:
        account_name: 'High Interest Savings Account'
        xpath: '//*[@id="accounts"]/div[68]/div/div'
      - account:
        account_name: 'Simplii Financial Savings Account'
        xpath: 'none'


  - financial_institution:
    name: 'CIBC'
    url: 'https://www.cibc.com/en/interest-rates/personal-bank-account-rates.html'
    id: 'none'
    table: "table"
    accounts:
      - account:
        account_name: 'eAdvantage_Savings'
        xpath: '//*[@id="blq-content"]/div[5]'
      - account: 
        account_name: 'Bonus_Savings'
        xpath: '//*[@id="blq-content"]/div[6]'
      - account:
        account_name: 'Premium_Growth'
        xpath: '//*[@id="blq-content"]/div[7]'
      - account:
        account_name: 'US_Personal'
        xpath: 'none'
      - account:
        account_name: 'Youth'
        xpath: 'none'

