name: Daily Build 

on:
  schedule:
  # 1100 hrs GMT is 0700 hrs EST
  - cron: "35 12 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 
        pip install -r ./rate-scanner/requirements.txt
    - name: Genarate Report
      run: |
        python ./rate-scanner/ExcelGenerator.py
    - name: Setup MSOffice Encrypt 
      run: |
        sudo apt install libssl-dev
        git clone https://github.com/herumi/cybozulib
        git clone https://github.com/herumi/msoffice
        cd msoffice
        make -j RELEASE=1
    # Not needed with email distribution
    # - name: Encrypt build file 
    #   run: |
    #     ./msoffice/bin/msoffice-crypt.exe -e -p CompetitiveTracker ./RateScanner.xlsx ./RateScanner.xlsx
    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
          name: Excel Report
          path: |
            RateScanner.xlsx

  release:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Download generated artifacts
        uses: actions/download-artifact@v2
        with:
          name: Excel Report

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Create GitHub Release
        id: create-new-release
        uses: actions/create-release@v1
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.date.outputs.date }}
          release_name: Release ${{ steps.date.outputs.date }}

      - name: Upload asset to Github Release
        uses: actions/upload-release-asset@v1
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url }}
          asset_path: ./RateScanner.xlsx
          asset_name: RateScanner_${{ steps.date.outputs.date }}.xlsx
          asset_content_type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet

  mail:
    runs-on: ubuntu-latest
    needs: [build]
    steps:    
      - name: Download generated artifacts
        uses: actions/download-artifact@v2
        with:
          name: Excel Report
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: in-v3.mailjet.com
          server_port: 587
          username: b6e65922a014dcc66ecf63de04a95369
          password: cf6c5c2641c9a3c641382a75ace52782
          subject: Rate Scanner Release
          to: Devarshi.Raval@cibc.com, Tatiana.Artemyeva@cibc.com
          from: Competitive Tracker <devarshi.raval@cibc.com>
          body: Hello, PFA the Rate Scanner sheet updated with the latest rates across all accounts.
          ignore_cert: true
          convert_markdown: true
          content_type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
          attachments: ./RateScanner.xlsx