name: Daily Build 

on:
  schedule:
  - cron: "50 20 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 
        if [ -f requirements.txt ]; then pip install -r ./rate-scanner/requirements.txt; fi
    - name: Genarate Report
      run: |
        python ./rate-scanner/ExcelGenerator.py
    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
          name: Excel Report
          path: |
            RateScanner.xlsx

  release:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Download generated artifacts
        uses: actions/download-artifact@v2
        with:
          name: Excel Report

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Create GitHub Release
        id: create-new-release
        uses: actions/create-release@v1
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.date.outputs.date }}
          release_name: Release ${{ steps.date.outputs.date }}

      - name: Upload asset to Github Release
        uses: actions/upload-release-asset@v1
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url }}
          asset_path: ./RateScanner.xlsx
          asset_name: RateScanner_${{ steps.date.outputs.date }}.xlsx
          asset_content_type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
