name: Daily Build 

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 
        pip install -r ./rate-scanner/requirements.txt
    - name: Genarate Report
      run: |
        python ./rate-scanner/ExcelGenerator.py
    - name: Setup MSOffice Encrypt 
      run: |
        git clone https://github.com/herumi/cybozulib
        git clone https://github.com/herumi/msoffice
        cd msoffice
        make -j RELEASE=1
    - name: Encrypt build file 
      run: |
        ./msoffice/bin/msoffice-crypt.exe -e -p CompetitiveTracker ./RateScanner.xlsx ./RateScanner.xlsx
    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
          name: Excel Report
          path: |
            RateScanner.xlsx

  mail:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Download generated artifacts
        uses: actions/download-artifact@v2
        with:
          name: Excel Report
    
      - name: SendGrid
        uses: peter-evans/sendgrid-action@v1
        env:
          SENDGRID_API_KEY: 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 
