name: Test Build 

on: workflow_dispatch

jobs:
  mail:
    runs-on: ubuntu-latest
    steps:    
      - name: SendGrid
        uses: peter-evans/sendgrid-action@v1
        env:
          SENDGRID_API_KEY: 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 
